export {default as Details} from './details/Details'
export {default as Header} from './header/Header'
export {default as Navbar} from './navbar/Navbar'
export {default as Storage} from './storage/Storage'
export {default as Footer} from './footer/Footer'